<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{7de039f4-eca8-4806-a063-3ce089714fb6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	blockgolf1: FB_Blokgolf;
	bTest: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF bTest THEN
	blockgolf1.M_Start(T#2S, T#1S);
END_IF;

blockgolf1();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="18" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>